# Generated by Django 3.1 on 2020-08-17 14:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cars_models', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarRate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')])),
            ],
        ),
        migrations.RemoveField(
            model_name='car',
            name='rate',
        ),
        migrations.CreateModel(
            name='GiveRate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cars_models.car')),
                ('care_rate_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cars_models.carrate')),
            ],
        ),
        migrations.AddField(
            model_name='car',
            name='rate',
            field=models.ManyToManyField(related_name='care_rate', to='cars_models.CarRate'),
        ),
    ]
