# Generated by Django 3.1 on 2020-08-15 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars_models', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='rate',
            field=models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')]),
        ),
    ]
