# Generated by Django 3.1 on 2020-08-16 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars_models', '0002_auto_20200815_0835'),
    ]

    operations = [
        migrations.CreateModel(
            name='CareRate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')])),
            ],
        ),
        migrations.RemoveField(
            model_name='car',
            name='rate',
        ),
        migrations.AddField(
            model_name='car',
            name='rate',
            field=models.ManyToManyField(related_name='care_rate', to='cars_models.CareRate'),
        ),
    ]
