# Generated by Django 3.1 on 2020-08-16 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars_models', '0003_auto_20200816_1344'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CareRate',
            new_name='CarRate',
        ),
    ]
