# Generated by Django 3.1 on 2020-08-16 13:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cars_models', '0004_auto_20200816_1347'),
    ]

    operations = [
        migrations.CreateModel(
            name='GiveRate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cars_models.car')),
                ('care_rate_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cars_models.carrate')),
            ],
        ),
        migrations.AlterField(
            model_name='car',
            name='rate',
            field=models.ManyToManyField(related_name='care_rate', through='cars_models.GiveRate', to='cars_models.CarRate'),
        ),
    ]
