# Generated by Django 3.1 on 2020-08-16 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars_models', '0006_auto_20200816_1358'),
    ]

    operations = [
        migrations.RenameField(
            model_name='carrate',
            old_name='rate',
            new_name='rating',
        ),
        migrations.AlterField(
            model_name='car',
            name='rate',
            field=models.ManyToManyField(related_name='care_rate', through='cars_models.GiveRate', to='cars_models.CarRate'),
        ),
    ]
